name: paratextlite
base: core20 # the base snap is the execution environment for this snap
version: '9.5.17.113'
summary: Paratext Lite running on the desktop
description: |
  Lite version of Paratext.
  Supports:
  S/R, Notes, Resources, Wordlists, Biblical Terms, Parallel Passages,
  Project history, My Tasks and more...

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' instead of 'devmode' once you have the right plugs and slots
icon: snap/gui/paratextlite.png
type: app
architectures:
  - build-on: [amd64]
    run-on: [amd64]
  - build-on: [amd64]
    run-on: [arm64]
  - build-on: [arm64]
    run-on: [arm64]

# We need snapd 2.55 or later to have the needed support for the
# `cups` interface in snapd
assumes:
  - snapd2.55

# this is not used or needed for anything other than to trigger automatic
# installation of the cups snap via "default-provider: cups"
plugs:
  print-install-cups:
    interface: content
    content: print
    default-provider: cups
    target: $SNAP_DATA/print

apps:
  paratextlite:
    command: start.sh
    extensions: [gnome-3-38]
    plugs:
      - network-bind
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
      - hardware-observe
      - removable-media
      - cups
    environment:
      PYTHONPYCACHEPREFIX: $SNAP_USER_COMMON/.cache/pycache

parts:
  paratextlite-part:
    # See 'snapcraft plugins'
    plugin: dump
    source:
      - on amd64 to amd64: package/Linux
      - on amd64 to arm64: package/LinuxArm64
      - on arm64: package/LinuxArm64
    stage-packages:
      - on amd64 to arm64:
        - "libicu66:arm64"
        - "libxshmfence1:arm64"
        - "libatk1.0-0:arm64"
        - "libgtk-3-0:arm64"
        - "libdrm2:arm64"
        - "libgbm1:arm64"
        - "libcurl4:arm64"
        - "liblttng-ust0:arm64"
        - "libasound2:arm64"
        - "libgconf-2-4:arm64"
        - "libnotify4:arm64"
        - "libnspr4:arm64"
        - "libnss3:arm64"
        - "libpcre3:arm64"
        - "libpulse0:arm64"
        - "libxss1:arm64"
        - "libxtst6:arm64"
        - "libx11-xcb1:arm64"
        - "libgdk-pixbuf2.0-0:arm64"
        - "fonts-roboto:arm64"
      - else:
        - libicu66
        - libxshmfence1
        - libatk1.0-0
        - libgtk-3-0
        - libdrm2
        - libgbm1
        - libcurl4
        - liblttng-ust0
        - libasound2
        - libgconf-2-4
        - libnotify4
        - libnspr4
        - libnss3
        - libpcre3
        - libpulse0
        - libxss1
        - libxtst6
        - libx11-xcb1
        - libgdk-pixbuf2.0-0
        - fonts-roboto
    stage-snaps: [mercurial]
  assets-part:
    plugin: dump
    source: package/Assets
    organize:
      '*' : Assets/
  fonts-part:
    plugin: dump
    source: fonts
    organize:
      '*' : Assets/fonts/
  resources-part:
    plugin: dump
    source: _Resources
    organize:
      '*' : Assets/Paratext8Projects/_Resources/
  dictionaries-part:
    plugin: dump
    source: _Dictionaries
    organize:
      '*' : Assets/Paratext8Projects/_Dictionaries/
  scripts-part:
    plugin: dump
    source: scripts

  ibus-part:
    plugin: dump
    source:
      - on amd64 to amd64: ibus/Linux
      - on amd64 to arm64: ibus/LinuxArm64
      - on arm64: ibus/LinuxArm64

layout:
  /usr/bin/hg:
    symlink: $SNAP/bin/hg
